#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Tomáš Havlas <tomas@havlas.me>
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# Enforce commit message format using Commitizen.
git cz check --allow-abort --commit-msg-file "$1"
