# SPDX-FileCopyrightText: 2024 Tomáš Havlas <tomas@havlas.me>
# SPDX-License-Identifier: Apache-2.0

---
namespace: havlasme
name: ansible
version: 0.3.1
readme: README.md
authors:
- Tomáš Havlas <tomas@havlas.me>
description: An Ansible Collection of modules and plugins used by havlasme collections and roles.
license:
- Apache-2.0
license_file: LICENSE
tags:
- ansible
repository: https://gitlab.com/havlas.me/ansible-collection-ansible
documentation: https://gitlab.com/havlas.me/ansible-collection-ansible
homepage: https://gitlab.com/havlas.me/ansible-collection-ansible
issues: https://gitlab.com/havlas.me/ansible-collection-ansible/-/issues
build_ignore:
- .ansible-lint
- .cache
- .editorconfig
- .gitignore
- .gitlab-ci.yml
- .idea
- .yamllint
- dist
- Makefile
- roles/*/.ansible-lint
- roles/*/.yamllint
...
